v1

diff --git a/sagemaker_triton/serve b/sagemaker_triton/serve
--- a/sagemaker_triton/serve
+++ b/sagemaker_triton/serve
@@ -1,23 +1,58 @@
 #!/bin/bash
 
-# # Set the directory to check
-# base_dir="/opt/ml/model/"
-# export SAGEMAKER_BIND_TO_PORT=${SAGEMAKER_BIND_TO_PORT:-8080}
+set -e  # Exit immediately if a command exits with a non-zero status.
 
-# # Check if the directory exists
-# if [ ! -d "$base_dir" ]; then
-#     echo "Error: $base_dir directory does not exist"
-#     exit 1
-# fi
+# Set the directory to check
+base_dir="/opt/ml/model/"
+export SAGEMAKER_BIND_TO_PORT=${SAGEMAKER_BIND_TO_PORT:-8080}
+
+# Check if the directory exists
+if [ ! -d "$base_dir" ]; then
+    echo "Error: $base_dir directory does not exist"
+    exit 1
+fi
 
 # Find the first subdirectory in the base directory
-# model_dir=$(find "$base_dir" -mindepth 1 -maxdepth 1 -type d -print -quit)
-# python3 /app/ssh_helper_start.py
-model_repo_path=/opt/ml/model
-python3 /app/ssh_helper_start.py
+model_dir=$(find "$base_dir" -mindepth 1 -maxdepth 1 -type d -print -quit)
 
-tritonserver --model-repository $model_repo_path \
-            --pinned-memory-pool-byte-size=2048000000 \
-            --cuda-memory-pool-byte-size=0:4096000000 \
-            --http-port 10086 \
-            --metrics-port 1
+# Check if a subdirectory was found
+if [ -z "$model_dir" ]; then
+    echo "No subdirectory found"
+    exit 0
+else
+    # Set the model_path
+    model_path="$model_dir"
+    
+    echo "Found model directory" $model_dir
+
+    if [ -f "$model_dir/triton_client.py" ]; then
+        # If triton_client.py file exists, proceed with setup
+        cp -r $base_dir/model_data/* /workspace/ || { log "Failed to copy model data"; exit 1; }
+        echo "Copied ${model_dir} files to workspace"
+
+        echo "Contents of /workspace:"
+        ls -R /workspace
+
+        # download triton model from s3
+        python3 ssh_helper_start.py || { echo "SSH helper start failed"; exit 1; }
+        
+        python3 download_model_from_s3.py || { echo "S3 sync failed"; exit 1; }
+        
+        # Start Triton server and run client
+        chmod +x /workspace/start_triton_and_client.sh
+        /workspace/start_triton_and_client.sh
+    else
+        echo "Error: triton_client.py not found in $model_dir"
+        exit 1
+    fi
+
+fi
+
+# Cleanup function
+cleanup() {
+    if [ ! -z "$triton_pid" ]; then
+        kill $triton_pid
+    fi
+}
+
+trap cleanup EXIT
